
version: 2

# sources:
#   - name: san_francisco
#     schema: public
#     tables:
#       - name: bikeshare_trips
#       - name: bikeshare_stations


models:
    - name: bikeshare_stations
      description: "make a copy of the stations table"
      columns:
          - name: station_id
          - name: name
          - name: latitude
          - name: longitude
          - name: dockcount
          - name: landmark
          - name: installation_date

    - name: bikeshare_trips
      description: "make a copy of the trips table"
      columns:
          - name: trip_id
            tests:
              - unique
              - not_null
          - name: duration_sec
            tests: 
              - not_null
          - name: start_date
          - name: start_station_name
          - name: start_station_id
          - name: end_date
          - name: end_station_name
          - name: end_station_id
          - name: bike_number
          - name: zip_code
            tests:
              - not_null
          - name: subscriber_type

    # - name: my_second_dbt_model
    #   description: "A starter dbt model"
    #   columns:
    #       - name: id
    #         description: "The primary key for this table"
    #         tests:
    #             - unique
    #             - not_null

